### ISSUE TITLE
Need Mobile Version

### ISSUE THREAD

**Issue by Kenford20** [Kenford20/Kodo-Namaewas-Heroku#1]
Game was designed to be played with friends either together or elsewhere, so the game will most likely be played on mobile devices (don't currently have a mobile view)

**Comment by Nysosis** [comment]
I have an old repo (not on GitHub currently) with some work I did a while back (last commit was Feb 2016) on creating a board generator/randomiser. I never put any game logic or multi-player functionality into it, I was just seeing it as a mobile tool for random layouts. But you think it could be of any use let me know.

![codenames](https://user-images.githubusercontent.com/5476382/48610398-ae0b6900-e97c-11e8-976d-8bb134890e7a.gif)
